### ISSUE TITLE
(little bit urgent) whomds children not doing the anchored part

### ISSUE THREAD

**Issue by CarolinaFellinghauer** [lindsayevanslee/whomds#12]
whomds is somehow getting into trouble once having to start the anchored part - the error message relates to a rowbinding issue, where the number of rows differ...
(MDS-Chile are running their analyses and you know, they already have their impossible time line etc...If I have time I may try to localise the error, but I am sure that you are much faster for that, probably it is just a little fix  ... )

**Comment by lindsayevanslee** [comment]
@CarolinaFellinghauer A new version of whomds was just released to CRAN. Closing this issue but let me know if there's still a problem
