### ISSUE TITLE
package update (?rlang) affects adult syntax

### ISSUE THREAD

**Issue by CarolinaFellinghauer** [lindsayevanslee/whomds#13]
Hi Lindsay, something makes problems in the adult syntax. See below the error message. Best wishes
Carolina

Rasch Model completed.
Error in `cli_block()`:
! `x` must not contain list or matrix columns:
✖ invalid columns at index(s): 1
Run `rlang::last_error()` to see where the error occurred.
Warning message:
The `x` argument of `as_tibble.matrix()` must have unique column names if `.name_repair` is
omitted as of tibble 2.0.0.
ℹ Using compatibility `.name_repair`.
ℹ The deprecated feature was likely used in the whomds package.
  Please report the issue at <https://github.com/lindsayevanslee/whomds/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
>

**Comment by lindsayevanslee** [comment]
@CarolinaFellinghauer I think this was fixed in the new version, closing issue but let me know if there are more problems
