### ISSUE TITLE
spanish accents in vignette

### ISSUE THREAD

**Issue by CarolinaFellinghauer** [lindsayevanslee/whomds#3]
looking at the vignettes (now rasch adults) in the R-Studio viewer, the viewer cannot show letters with accents and puts question mark instead.

https://tex.stackexchange.com/questions/8857/how-to-type-special-accented-letters-in-latex

**Comment by CarolinaFellinghauer** [comment]
@lindsayevanslee ... I think that maybe you did not receive my previous messages because did not assign them properly... sorry... or rather thank you for giving me an opportunity to learn how to use GitHub.
- the Spanish accents, which did not look like letters in the vignette.
-x-axis of figures - I think specifically the density line- I would like to change the labels
- potentially already put automatically a (or two if doing it also for capacity) variable with disability group labels in the datawabilities.csv file
Thank you!

**Comment by lindsayevanslee** [comment]
@CarolinaFellinghauer For the original issue on Spanish accents: in my RStudio viewer they render fine. Can you give more detail on how you are accessing the vignettes? What I did for example was run `vignette("c1_background_ES", package = "whomds")`. Are you doing something different? 

And for the other things you mentioned in the second message, can you open separate issues for those items and give more detail on what is needed? Thanks!
