### ISSUE TITLE
tidyr update requires changing nest() and unnest() function call

### ISSUE THREAD

**Issue by CarolinaFellinghauer** [lindsayevanslee/whomds#6]
there was a warning .key deprecated. After adjusting for that only the warning message seems to disappear, outputs seem to remain the same... but anyway, nest() and unnest() have been changed with tidyr package updates at some point - but as the update caused quite some issues in users, the tidyr package maintainer created functions nest_legacy() and unnest_legacy()... as I discovered the existence of the '_legacy' syntaxes only when trying to fix unnest(), the first function nest() is probably fixed more properly, working with the newest versions.

rasch_df_nest 

function (df, vars_group, vars_id)
{
  df_nest <- df %>% filter(!is.na(!!rlang::sym(vars_group)))
  df_nest <- df_nest %>% group_by_at(vars_group) %>%

 tidyr::nest(df_split = !group_cols()) %>%

    mutate(df_split = purrr::map(df_split, function(df_age) {
      df_age <- bind_rows(df_age, df %>% filter(!!rlang::sym(vars_id) %in%
                                                  c("MAX", "MIN")))
    }))
  return(df_nest)
}

rasch_rescale_children_updated 

function(df, df_nest, vars_group, vars_id){
 
  if ("WLE_anchored" %in% names(df_nest)) {
    df_final <- df_nest %>% dplyr::mutate(df_split = purrr::map2(df_split,
                                                                 WLE_anchored, function(df_age, WLE_age) {
                                                                   df_age <- df_age %>% tibble::add_column(person_pars = WLE_age$theta)
                                                                   return(df_age)
                                                                 })) %>% dplyr::select(c(vars_group, "df_split")) %>%

      tidyr::unnest_legacy()

  }else {
    df_final <- df %>% tibble::add_column(person_pars = df_nest$WLE_multigroup[[1]]$theta)
  }
  df_final <- df_final %>% dplyr::mutate(rescaled = scales::rescale(person_pars,
                           c(0, 100))) %>% dplyr::filter_at(vars(vars_id), any_vars(. != "MAX")) %>% dplyr::filter_at(vars(vars_id), any_vars(. !=
                                                                                                                                                                                      "MIN"))
   return(df_final)
}

**Comment by lindsayevanslee** [comment]
@CarolinaFellinghauer I think I have fixed this now. Can you install the latest development version and see if you still have any issues with this?
