### ISSUE TITLE
Spanish ñ and é not an issue anymore

### ISSUE THREAD

**Issue by CarolinaFellinghauer** [lindsayevanslee/whomds#8]
Spanish accents, which did not look like letters in the vignette...

this issue is not an issue anymore. I was opening the vignette from inside R - Studio - (going on the package list, clicking on WHOMDS and than selecting the vignettes). Maybe that was an issue in R-Studio that got fixed, because the viñettes look good know. 
... so issue solved...

**Comment by lindsayevanslee** [comment]
duplicate of #3
